# Generated by Django 5.2.1 on 2025-05-10 10:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='personal_academics_models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userCGPA', models.CharField(max_length=255)),
                ('hackathonNo', models.IntegerField()),
                ('leetcodeNo', models.IntegerField()),
                ('contestNo', models.IntegerField()),
                ('yearofaddmission', models.DateField(default=django.utils.timezone.now)),
                ('passoutyear', models.DateField(default=django.utils.timezone.now)),
                ('university_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='personal_details_models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='someone', max_length=255, unique=True)),
                ('userdept', models.CharField(default='None', max_length=255, null=True)),
                ('userAge', models.CharField(default='None', max_length=255, null=True)),
                ('userDOB', models.DateField(default=django.utils.timezone.now)),
                ('userimage', models.ImageField(blank=True, null=True, upload_to='user_images/')),
                ('userbio', models.TextField(blank=True, null=True)),
                ('university_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='personal_skill_models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.CharField(choices=[('AIML', 'AI & ML'), ('AI', 'AI'), ('ML', 'ML'), ('UIUX', 'UI & UX'), ('Backend', 'Backend'), ('Frontend', 'Frontend')], max_length=255, null=True)),
                ('hobbies', models.CharField(max_length=255, null=True)),
                ('sleep_schedule', models.CharField(choices=[('EarlyBirds', 'Early Birds'), ('NightOwl', 'Night Owl'), ('Any', 'No Such Schedule')], max_length=255, null=True)),
                ('university_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='personal_team_models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=255, unique=True)),
                ('team_project_topic', models.CharField(max_length=255, unique=True)),
                ('is_open', models.BooleanField(default=True)),
                ('team_members', models.ManyToManyField(related_name='teams', to=settings.AUTH_USER_MODEL)),
                ('university_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_teams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
