# Generated by Django 5.2.1 on 2025-05-11 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainmodel', '0002_profile_score_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='personal_connections_models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connections', models.ManyToManyField(related_name='connections_made', to=settings.AUTH_USER_MODEL)),
                ('university_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
